BilgeAdamGuney/BilgeAdamGuney/Controllers/ProductController.cs
using BilgeAdamGuney.ActionFilters;
using BilgeAdamGuney.DataAccess.Context;
using BilgeAdamGuney.DataAccess.Entities;
using BilgeAdamGuney.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BilgeAdamGuney.Controllers
{
    public class ProductController : Controller
    {
        [AuthorizationControl(RoleId = 2)]
        public ActionResult Index()
        {
            try
            {
                ProductListModel model = null;
                List<Product> listProduct = null;
                List<ProductListModel> listProductModel = new List<ProductListModel>();
                using (InteriorContext db = new InteriorContext())
                {
                    listProduct = db.Product.ToList();

                    foreach (var item in listProduct)
                    {
                        model = new ProductListModel();
                        model.Name = item.Name.ToUpper();
                        model.Price = item.Price;
                        model.UnitsInStock = item.UnitsInStock;
                        model.ProductType = item.ProductType;
                        model.ImagePath = item.ImagePath;

                        listProductModel.Add(model);
                    }
                }

                return View(listProductModel);
            }
            catch (Exception)
            {

                throw;
            }
        }
        [AuthorizationControl(RoleId = 2)]
        public ActionResult Create()
        {
            FillCategoryDropDown();
            return View();
        }
        [HttpPost]
        [AuthorizationControl(RoleId = 2)]
        public ActionResult Create(ProductCreateModel model)
        {
            try
            {
                FillCategoryDropDown();

                if (model.Name == null||model.Name.Length<2)
                    ModelState.AddModelError("Name", "Ürün ismi çok kısa veya boş");

                if (!ModelState.IsValid)
                    return View();

                using (InteriorContext db = new InteriorContext())
                {
                    Product product = new Product();
                    product.Name = model.Name;
                    product.Description = model.Description;
                    product.Price = model.Price;
                    product.UnitsInStock = model.UnitsInStock;
                    product.ProductTypeId = model.ProductTypeId;
                    if (model.ImageFile != null)
                        product.ImagePath = SavePhoto(model.ImageFile);
                    else
                        product.ImagePath = "/assets/img/owner/defaultImage.jpg";

                    db.Entry(product).State = System.Data.Entity.EntityState.Added;
                    db.SaveChanges();
                    TempData["SuccessMessage"] = "Ürün başarıyla eklendi";
                }
                return View();
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Ürün ekleme sırasında hata meydana geldi: " + ex;
                return View(model);
            }
        }
        
        public ActionResult Single(int id)
        {
            ProductListModel product = null;
            try
            {
                using (InteriorContext db = new InteriorContext())
                {
                    product = db.Product.Include("ProductType.Products").Where(m => m.Id == id)
                        .Select(m => new ProductListModel()
                        {
                            Id = m.Id,
                            Name = m.Name,
                            Description = m.Description,
                            Price = m.Price,
                            ImagePath = m.ImagePath,
                            ProductTypeId = m.ProductTypeId,
                            ProductType = m.ProductType,
                            UnitsInStock = m.UnitsInStock
                        }).SingleOrDefault();
                TempData["SimilarProducts"] = product.ProductType.Products.ToList();
                }
            }
            catch (Exception)
            {

                throw;
            }
            
            return View(product);
        }

        public void FillCategoryDropDown()
        {
            using (InteriorContext db = new InteriorContext())
            {
                SelectList productSelectList = new SelectList(db.ProductType.ToList(), "Id", "Name");
                ViewBag.ProductTypes = productSelectList;
            }
        }

        
        public string SavePhoto(HttpPostedFileBase file)
        {
            try
            {
                if (file != null && file.ContentLength > 0)
                    file.SaveAs(Server.MapPath("~/assets/img/saved/" + file.FileName));
                
                return "/assets/img/saved/" + file.FileName;
            }
            catch (Exception ex)
            {
                throw new Exception("Resim kaydetme sırasında hata meydana geldi" + ex);
            }
        }
    }
}

BilgeAdamGuney/BilgeAdamGuney/Controllers/ProductTypeController.cs
using BilgeAdamGuney.ActionFilters;
using BilgeAdamGuney.DataAccess.Context;
using BilgeAdamGuney.DataAccess.Entities;
using BilgeAdamGuney.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BilgeAdamGuney.Controllers
{
    public class ProductTypeController : Controller
    {
        
        public ActionResult Index(int id)
        {
            try
            {
                List<Product> listProduct = null;
                using (InteriorContext db = new InteriorContext())
                {
                    ProductType item = db.ProductType.Where(m => m.Id == id).SingleOrDefault();
                    listProduct = item.Products;
                }
                return View(listProduct);
            }
            catch (Exception)
            {

                throw;
            }
        }
        [AuthorizationControl(RoleId = 2)]
        public ActionResult Create()
        {
            FillCategoryDropDown();
            return View();
        }

        [HttpPost]
        [AuthorizationControl(RoleId = 2)]
        public ActionResult Create(ProductTypeCreateModel model)
        {
            try
            {
                FillCategoryDropDown();
                if (model.Name == null)
                    throw new Exception("Tür ismi boş geçilemez.");

                using (InteriorContext db = new InteriorContext())
                {
                    ProductType productType = new ProductType();
                    productType.Name = model.Name;
                    productType.CategoryId = model.CategoryId;
                    db.Entry(productType).State = System.Data.Entity.EntityState.Added;
                    db.SaveChanges();
                    TempData["SuccessMessage"] = "Tür başarıyla eklendi";
                }
                return View();
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Kaydetme sırasında bir hata meydana geldi: " + ex;
                return View(model);
            }
        }

        public void FillCategoryDropDown()
        {
            using (InteriorContext db = new InteriorContext())
            {
                SelectList categorySelectList = new SelectList(db.Category.ToList(), "Id", "Name");
                ViewBag.Categories = categorySelectList;
            }
        }
    }
}

BilgeAdamGuney/BilgeAdamGuney/Views/ProductType/Create.cshtml
@using BilgeAdamGuney.Models
@model ProductTypeCreateModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 class="page-header">Yeni Ürün Türü Ekleme</h2>
@using (Html.BeginForm("Create", "ProductType", FormMethod.Post))
{
    if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success form-group row">
            @TempData["SuccessMessage"]
        </div>
    }
    else if (TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-danger form-group row">
            @TempData["ErrorMessage"]
        </div>
    }

    <div class="form-group row">
        @Html.LabelFor(m => m.Name, "Tür Adı")
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
    </div>
    <div class="form-group row">
        @Html.LabelFor(m => m.CategoryId, "Kategori")
        @Html.DropDownListFor(m => m.CategoryId, (SelectList)ViewBag.Categories, new { @class = "form-control" })
    </div>
    <div class="form-group row">
        <div class="col-xs-12 text-right">
            <button type="reset" class="btn btn-rounded btn-inline btn-warning">Temizle</button>
            <button type="submit" class="btn btn-rounded btn-inline btn-primary">Kaydet</button>
        </div>
    </div>
}

@section scripts{
    <script>

        $(function ()
        {
            var timer;
            window.addEventListener('load', function ()
            {
                $(".alert").slideDown("slow");
                debugger;
                clearTimeout(timer);
                var ms = 3000; // milliseconds
                timer = setTimeout(function ()
                {
                    debugger;
                    $(".alert.alert-success").slideUp("slow");
                }, ms);
            });
        });

        $("#create_form").validate(
            {
                rules:
                {
                    Name: { required: true, maxlength: 50, minlength: 2 }
                },
                messages:
                {
                    Name: { required: "<div class=\"alert alert-danger\">Tür ismi alanı boş bırakılamaz</div>", maxlength: "<div class=\"alert alert-danger\">50 karakterden uzun olamaz.</div>", minlength: "<div class=\"alert alert-danger\">Tür ismi 2 karaterden uzun olmalıdır</div>" }
                }
            });


    </script>
}

BilgeAdamGuney/BilgeAdamGuney/Views/ProductType/Index.cshtml
@using BilgeAdamGuney.DataAccess.Entities
@model List<Product>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="new-arrivals-w3agile">
    <div class="container">
        <h3 class="tittle1">@(Model.Count!=0?Model.First().ProductType.Name:string.Format("Bu kategoride ürün bulunmamaktadır."))</h3>
        <div class="arrivals-grids">
            @foreach (var item in Model)
            {
                <div class="col-md-3 arrival-grid simpleCart_shelfItem">
                    <div class="grid-arr">
                        <div class="grid-arrival">
                            <figure>
                                <a href="@Url.Action("Single", "Product", new {id=item.Id })">
                                    <div class="grid-img">
                                        <img src="@item.ImagePath" class="img-responsive" alt="">
                                    </div>
                                </a>
                            </figure>
                        </div>
                        <div class="women">
                            <h6><a href="@Url.Action("Single", "Product", new {id=item.Id })">@item.Name</a></h6>
                            <p><em class="item_price">@item.Price TL</em></p>
                            <a href="#" data-text="Add To Cart" data-product-id=@item.Id class="my-cart-b item_add sepete-ekle">Sepetime Ekle</a>
                        </div>
                    </div>
                </div>
            }
            <div class="clearfix"></div>
        </div>
    </div>
</div>