BilgeAdamGuney/BilgeAdamGuney/Controllers/AddressController.cs
using BilgeAdamGuney.ActionFilters;
using BilgeAdamGuney.DataAccess.Context;
using BilgeAdamGuney.DataAccess.Entities;
using BilgeAdamGuney.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BilgeAdamGuney.Controllers
{
    [AuthorizationControl(RoleId = 1)]
    public class AddressController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            FillCityDropDown();
            return View();
        }

        [HttpPost]
        public ActionResult Create(AddressCreateModel model)
        {
            try
            {
                FillCityDropDown();
                Member member = null;
                if (Session["Member"] != null)
                    member = (Member)Session["Member"];
                using (InteriorContext db = new InteriorContext())
                {
                    Address address = new Address();
                    address.Name = model.Name;
                    address.Description = model.Description;
                    address.DistrictId = model.DistrictId;
                    address.MemberId = member.Id;

                    db.Entry(address).State = System.Data.Entity.EntityState.Added;
                    db.SaveChanges();
                    TempData["SuccessMessage"] = "Adresiniz başarıyla kaydedildi";
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Adres kaydetme sırasında hata meydana geldi" + ex;
            }

            return View();
        }

        public void FillCityDropDown()
        {
            using (InteriorContext db = new InteriorContext())
            {
                ViewBag.CityList = new SelectList(db.City.ToList(), "Id", "Name");
                ViewBag.DistrictList = new SelectList(db.District.ToList(), "Id", "Name");
            }
        }

        public ActionResult GetDistrictsByCity(int cityId)
        {
            SelectList listDistrict = null;
            using (InteriorContext db = new InteriorContext())
            {
                listDistrict = new SelectList(db.District.Where(m => m.CityId == cityId).ToList(),"Id","Name");
            }

            return Json(listDistrict, JsonRequestBehavior.AllowGet);
        }
    }
}

BilgeAdamGuney/BilgeAdamGuney/Controllers/OrderController.cs
using BilgeAdamGuney.ActionFilters;
using BilgeAdamGuney.DataAccess.Context;
using BilgeAdamGuney.DataAccess.Entities;
using BilgeAdamGuney.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BilgeAdamGuney.Controllers
{
    public class OrderController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        [AuthorizationControl(RoleId =1)]
        public ActionResult GetByMember(int id)
        {
            List<OrderModel> listOrder = null;
            try
            {
                using (InteriorContext db = new InteriorContext())
                {
                    listOrder = db.Order.Where(m => m.MemberId == id)
                        .Select(m => new OrderModel()
                        {
                            MemberId = m.MemberId,
                            OrderAddress = m.OrderAddress,
                            OrderAddressId = m.OrderAddressId,
                            District = m.OrderAddress.District,
                            City = m.OrderAddress.District.City,
                            OrderDate = m.OrderDate,
                            RequiredDate = m.RequiredDate,
                            ShippedDate = m.ShippedDate,
                            OrderDetails = m.OrderDetails,
                            Id = m.Id
                        }
                    ).ToList();
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Siparişlerin gösterimi sırasında hata meydana geldi" + ex;
            }

            return View(listOrder);
        }

        [AuthorizationControl(RoleId = 1)]
        public ActionResult GetOrderProducts(int id)
        {
            List<OrderDetailModel> listOrderDetail = null;
            using (InteriorContext db = new InteriorContext())
            {
                listOrderDetail = db.OrderDetail.Where(m => m.OrderId == id)
                    .Select(m=>new OrderDetailModel()
                    {
                        ProductId=m.ProductId,
                        Product=m.Product,
                        ImagePath=m.Product.ImagePath,
                        Price=m.Product.Price,
                        Name=m.Product.Name
                    }
                    ).ToList();
            }

            return View(listOrderDetail);
        }
        [AuthorizationControl(RoleId = 1)]
        public ActionResult Create()
        {
            if (Session["Member"] == null)
                return RedirectToAction("SignIn", "Member");

            return View(FillAddressDropdown());
        }

        [HttpPost]
        [AuthorizationControl(RoleId = 1)]
        public ActionResult Create(OrderModel model)
        {
            DbContextTransaction transaction;
            using (InteriorContext db = new InteriorContext())
            {
                transaction = db.Database.BeginTransaction(System.Data.IsolationLevel.ReadCommitted);

                try
                {
                    Cart cart = null;
                    if (Session["Cart"] != null)
                        cart = Cart.CurrentCart;

                    Member member = null;
                    if (Session["Member"] != null)
                        member = (Member)Session["Member"];
                    else
                        return RedirectToAction("SignIn", "Member");

                    if (cart.CartProducts.Count == 0)
                    {
                        TempData["ErrorMessage"] = "Sepetinizde Ürün Yok";
                        return RedirectToAction("Index", "Cart");
                    }

                    Order order = new Order();
                    order.MemberId = member.Id;
                    order.OrderAddressId = model.OrderAddressId;
                    order.OrderDate = DateTime.Now;
                    db.Entry(order).State = EntityState.Added;
                    db.SaveChanges();

                    OrderDetail orderDetail = null;
                    foreach (var item in cart.CartProducts)
                    {
                        orderDetail = new OrderDetail();
                        orderDetail.ProductId = item.ProductId;
                        orderDetail.Quantity = item.Quantity;
                        orderDetail.UnitPrice = item.TotalAmount;
                        orderDetail.OrderId = order.Id;
                        db.Entry(orderDetail).State = EntityState.Added;
                    }
                    db.SaveChanges();
                    transaction.Commit();
                    Cart.Clear();
                    TempData["SuccessMessage"] = "Siparişiniz Onaylandı!";
                }
                catch (Exception ex)
                {
                    TempData["ErrorMessage"] = "Sipariş alınırken hata meydana geldi" + ex;
                    transaction.Rollback();
                }
                finally
                {
                    transaction.Dispose();
                }
            }
            return View(FillAddressDropdown());
        }


        public void FillCityAndDistrictDropDown()
        {
            using (InteriorContext db = new InteriorContext())
            {
                ViewBag.CityList = new SelectList(db.City.ToList(), "Id", "Name");
                ViewBag.DistrictList = new SelectList(db.District.ToList(), "Id", "Name");
            }
        }

        public OrderModel FillAddressDropdown()
        {
            Member member = null;
            if (Session["Member"] != null)
            {
                member = (Member)Session["Member"];
                using (InteriorContext db = new InteriorContext())
                {
                    Member memberFromDb = db.Member.Where(m => m.Id == member.Id).SingleOrDefault();
                    SelectList selectListAddress = new SelectList(memberFromDb.Addresses, "Id", "Name");
                    ViewBag.AddressList = selectListAddress;
                }
            }
            else
                member = new Member();

            OrderModel orderModel = new OrderModel();
            orderModel.Member = member;


            return orderModel;
        }
    }
}

BilgeAdamGuney/BilgeAdamGuney/Views/Order/Create.cshtml
@using BilgeAdamGuney.Models
@model OrderModel
@{
    ViewBag.Title = "Sipariş";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content">
    <!--login-->
    <div class="login">
        <div class="main-agileits">
            <div class="form-w3agile form1">
                <h2>Fatura Bilgileri</h2>   
                @using (Html.BeginForm("Create", "Order", FormMethod.Post, new { @id = "create11_form" }))
                {
                    if (TempData["SuccessMessage"] != null)
                    {
                        <div class="alert alert-success form-group row">
                            @TempData["SuccessMessage"]
                        </div>
                    }
                    else if (TempData["ErrorMessage"] != null)
                    {
                        <div class="alert alert-danger form-group row">
                            @TempData["ErrorMessage"]
                        </div>
                    }
                    <div class="form-group">
                        @Html.TextBoxFor(m=>m.Member.FirstName, new { @placeholder = "Adınız", @class = "form-control" })
                        @if (ViewData.ModelState["FirstName"] != null && ViewData.ModelState["FirstName"].Errors.Any())
                        {
                            <div class="alert alert-danger">
                                @Html.ValidationMessage("FirstName")
                            </div>
                        }
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.Member.LastName, new { @placeholder = "Soyadınız", @class = "form-control" })
                        @if (ViewData.ModelState["LastName"] != null && ViewData.ModelState["LastName"].Errors.Any())
                        {
                            <div class="alert alert-danger">
                                @Html.ValidationMessage("LastName")
                            </div>
                        }
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.Member.Phone, new { placeholder = "Telefon", @class = "form-control phone_us" })
                        @if (ViewData.ModelState["Phone"] != null && ViewData.ModelState["Phone"].Errors.Any())
                        {
                            <div class="alert alert-danger">
                                @Html.ValidationMessage("Phone")
                            </div>
                        }
                    </div>
                    <div class="form-group">
                        @Html.DropDownListFor(m=>m.OrderAddressId, (SelectList)ViewBag.AddressList, new {@class = "form-control" })
                        @if (ViewData.ModelState["OrderAddress"] != null && ViewData.ModelState["OrderAddress"].Errors.Any())
                        {
                            <div class="alert alert-danger">
                                @Html.ValidationMessage("OrderAddress")
                            </div>
                        }
                    </div>
                    @Html.ActionLink("Adres Ekle","Create","Address",null,new { @class="btn btn-primary",@style="float:right;" })
                    @Html.HiddenFor(m => m.MemberId)
                    <div class="form-group">
                        <button type="submit" style="margin-left:26%;" class="btn btn-rounded btn-inline btn-primary">Siparişi Tamamla</button>
                    </div>
                }
            </div>

        </div>
    </div>
    <!--login-->
</div>

@section scripts{


    <script>

        $(function ()
        {
            var timer;
            window.addEventListener('load', function ()
            {
                $(".alert").slideDown("slow");
                debugger;
                clearTimeout(timer);
                var ms = 3000; // milliseconds
                timer = setTimeout(function ()
                {
                    debugger;
                    $(".alert.alert-success").slideUp("slow");
                }, ms);
            });
        });

        var alertdiv = $("<div>");
        alertdiv.text("Şifre ve tekrarı uyuşmuyor");
        alertdiv.addClass("alert alert-danger");
        $(".confirm-password").append(alertdiv)
        alertdiv.hide();
        $('#PasswordConfirm').on('blur', function controlDifference()
        {
            if ($(this).val() != $('#Password').val())
                alertdiv.slideDown("fast");
            else
                alertdiv.slideUp("fast");
        });

        $(".phone_us").mask("(000) 000-0000");

    </script>
}

BilgeAdamGuney/BilgeAdamGuney/Views/Order/CreateAsGuest.cshtml
@using BilgeAdamGuney.Models
@model OrderCreateAsGuestModel
@{
    ViewBag.Title = "Sipariş";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content">
    <!--login-->
    <div class="login">
        <div class="main-agileits">
            <div class="form-w3agile form1">
                <h2>Fatura Bilgileri</h2>
                @using (Html.BeginForm("CreateAsGuest", "Order", FormMethod.Post, new { @id = "create11_form" }))
                {
                    if (TempData["SuccessMessage"] != null)
                    {
                        <div class="alert alert-success form-group row">
                            @TempData["SuccessMessage"]
                        </div>
                    }
                    else if (TempData["ErrorMessage"] != null)
                    {
                        <div class="alert alert-danger form-group row">
                            @TempData["ErrorMessage"]
                        </div>
                    }
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.FirstName, new { @placeholder = "Adınız", @class = "form-control" })
                        @if (ViewData.ModelState["FirstName"] != null && ViewData.ModelState["FirstName"].Errors.Any())
                        {
                            <div class="alert alert-danger">
                                @Html.ValidationMessage("FirstName")
                            </div>
                        }
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.LastName, new { @placeholder = "Soyadınız", @class = "form-control" })
                        @if (ViewData.ModelState["LastName"] != null && ViewData.ModelState["LastName"].Errors.Any())
                        {
                            <div class="alert alert-danger">
                                @Html.ValidationMessage("LastName")
                            </div>
                        }
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.Phone, new { placeholder = "Telefon", @class = "form-control phone_us" })
                        @if (ViewData.ModelState["Phone"] != null && ViewData.ModelState["Phone"].Errors.Any())
                        {
                            <div class="alert alert-danger">
                                @Html.ValidationMessage("Phone")
                            </div>
                        }
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.AddressDescription, new { placeholder = "Adres Açıklaması", @class = "form-control" })
                        @if (ViewData.ModelState["Phone"] != null && ViewData.ModelState["Phone"].Errors.Any())
                        {
                            <div class="alert alert-danger">
                                @Html.ValidationMessage("Phone")
                            </div>
                        }
                    </div>
                    <div class="form-group">
                        @Html.DropDownListFor(m => m.CityId, (SelectList)ViewBag.CityList, new { @id = "city", @class = "form-control" })
                        @if (ViewData.ModelState["city"] != null && ViewData.ModelState["city"].Errors.Any())
                        {
                            <div class="alert alert-danger">
                                @Html.ValidationMessage("city")
                            </div>
                        }
                    </div>
                    <div class="form-group">
                        @Html.DropDownListFor(m => m.DistrictId, (SelectList)ViewBag.DistrictList, new { @id = "district", @class = "form-control" })
                        @if (ViewData.ModelState["DistrictId"] != null && ViewData.ModelState["DistrictId"].Errors.Any())
                        {
                            <div class="alert alert-danger">
                                @Html.ValidationMessage("DistrictId")
                            </div>
                        }
                    </div>
                    <div class="form-group">
                        <button type="submit" style="margin-left:26%;" class="btn btn-rounded btn-inline btn-primary">Siparişi Tamamla</button>
                    </div>
                }
            </div>

        </div>
    </div>
    <!--login-->
</div>

@section scripts{


    <script>


        $("#city").change(function ()
        {
            debugger;
            var cityId = $(this).val();
            var districtDropdown = $("#district");

            if (cityId > 0)
            {

                $.ajax({
                    url: '@Url.Action("GetDistrictsByCity", "Address")',
                    method: 'POST',
                    data: { 'cityId': cityId },
                    success: function (data)
                    {
                        districtDropdown.html(addOption(data));
                    },
                    error: function (reponse)
                    {
                        debugger;
                        alert("error : " + reponse.responseText);
                    }
                });
            }

        })
        function addOption(response)
        {

            var items = "<option value=\"0\">Lütfen Seçiniz...</option>";

            $.each(response, function (i, district)
            {

                items += "<option value=\"" + district.Value + "\">" + district.Text + "</option>";

            });

            return items;

        }



        var alertdiv = $("<div>");
        alertdiv.text("Şifre ve tekrarı uyuşmuyor");
        alertdiv.addClass("alert alert-danger");
        $(".confirm-password").append(alertdiv)
        alertdiv.hide();
        $('#PasswordConfirm').on('blur', function controlDifference()
        {
            if ($(this).val() != $('#Password').val())
                alertdiv.slideDown("fast");
            else
                alertdiv.slideUp("fast");
        });

        $("#create11_form").validate(
            {
                rules:
                {
                    FirstName: { required: true, maxlength: 50, minlength: 2 },
                    LastName: { required: true, maxlength: 50, minlength: 2 },
                    Password: { required: true, maxlength: 20, minlength: 8 },
                    Phone: { required: true, maxlength: 14, minlength: 14 },
                    Email: { required: true, maxlength: 50, minlength: 5 }
                },
                messages:
                {
                    FirstName: { required: "<div class=\"alert alert-danger\">İsim alanı boş bırakılamaz</div>", maxlength: "<div class=\"alert alert-danger\">50 karakterden uzun olamaz.</div>", minlength: "<div class=\"alert alert-danger\">Kullanıcı adı 2 karaterden uzun olmalıdır</div>" },
                    LastName: { required: "<div class=\"alert alert-danger\" style=\"padding: 8px 5px;\">Soyad alanı boş bırakılamaz</div>", maxlength: "<div class=\"alert alert-danger\">50 karakterden uzun olamaz.</div>", minlength: "<div class=\"alert alert-danger\">Kullanıcı adı 2 karaterden uzun olmalıdır</div>" },
                    Password: { required: "<div class=\"alert alert-danger\">Şifre alanı boş bırakılamaz</div>", maxlength: "<div class=\"alert alert-danger\">20 karakterden uzun olamaz</div>", minlength: "<div class=\"alert alert-danger\">Şifreniz en az 8 karakter olmalıdır.</div>" },
                    Phone: { required: "<div class=\"alert alert-danger\">Telefon alanı boş bırakılamaz</div>", maxlength: "<div class=\"alert alert-danger\">10 karakterden uzun olamaz</div>", minlength: "<div class=\"alert alert-danger\">Telefon numarasını yanlış girdiniz.</div>" },
                    Email: { required: "<div class=\"alert alert-danger\">Email alanı boş bırakılamaz</div>", maxlength: "<div class=\"alert alert-danger\">50 karakterden uzun olamaz</div>", minlength: "<div class=\"alert alert-danger\">Email 5 karakterden kısa olamaz.</div>" }

                }
            });

        $(".phone_us").mask("(000) 000-0000");

    </script>
}

BilgeAdamGuney/BilgeAdamGuney/Views/Order/GetByMember.cshtml
@using BilgeAdamGuney.Models
@model List<OrderModel>
@{
    ViewBag.Title = "GetByMember";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="table-size" style="margin: 0 auto;">
    <h1 class="page-header">Sipariş Listesi</h1>
    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success">
            @TempData["SuccessMessage"]
        </div>
    }
    <div>
        @Html.TextBox("Search", null, new { @placeholder = "Arama", @class = "search form-control" })
        <div class="page-size-div">
            <p class="page-size">Görüntüleme boyutu :</p>
            @Html.DropDownList("PageSize", new SelectList(new Dictionary<string, int> { { "2", 2 }, { "10", 10 }, { "20", 20 }, { "100", 100 } }, "Key", "Value", 10), new { @class = "form-control", @style = "width:73px;" })
        </div>
    </div>
    <div id="test_container">
        <table id="myTable" class="table table-hover">
            <thead>
                <tr id="myRow">
                    <th class="col-xm-3 col-md-3" sorting" id="department_name" data-sort-by="Name">Sipariş Tarihi</th>
                    <th class="col-xm-1 col-md-2" sorting" id="department_name" data-sort-by="Name">Adres İsmi</th>
                    <th class="col-xm-1 col-md-4" sorting" id="department_name" data-sort-by="Name">Açıklama</th>
                    <th class="col-xm-1 col-md-4" sorting" id="department_name" data-sort-by="Name">İl / İlçe</th>
                    <th class="col-xm-6 col-md-6 sorting" data-sort-by="Description">Ürünler</th>
                    <th class="col-xm-3 col-md-3"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
            {
                    <tr>
                        <td class="col-xm-3 col-md-3">@item.OrderDate.Date</td>
                        <td class="col-xm-1 col-md-2">@item.OrderAddress.Name</td>
                        <td class="col-xm-1 col-md-4">@item.OrderAddress.Description... </td>
                        <td class="col-xm-1 col-md-4">@(item.District.Name+" / "+item.City.Name) </td>

                        <td class="col-xm-1 col-md-2">@Html.ActionLink("Ürünler","GetOrderProducts",new {id=item.Id },new { @class="btn btn-warning"})</td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

BilgeAdamGuney/BilgeAdamGuney/Views/Order/GetOrderProducts.cshtml
@using BilgeAdamGuney.Models
@model List<OrderDetailModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content">
    <div class="cart-items">
        <div class="container">
            <h2>Siparişi Verilen Ürünler (@Model.Count)</h2>
            
            @foreach (var item in Model)
            {
                <div class="cart-header">
                    <div class="cart-sec simpleCart_shelfItem">
                        <div class="cart-item cyc">
                            <img src="@item.Product.ImagePath" class="img-responsive" alt="">
                        </div>
                        <div class="cart-item-info">
                            <h3><a href="#"> @item.Product.Name </a></h3>

                            <div class="delivery">
                                <p>Toplam : @item.Product.Price</p>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                        <div class="clearfix"></div>

                    </div>
                </div>
            }
        </div>
    </div>
</div>